### ISSUE TITLE
No checksum for ubuntu-18.04.5-live-server-amd64.iso download

### ISSUE THREAD

**Issue by UnknownVictim** [canonical-web-and-design/ubuntu.com#10010]
From https://ubuntu.com/download/server, you download "ubuntu-18.04.5-live-server-amd64.iso".  The same page has a link to https://cdimage.ubuntu.com/releases/18.04.5/release/SHA256SUMS (Please check the "SHA256SUMS" page for the checksum numbers.) but the page does not include a checksum for the specific ISO.

Thank you.
---
*Reported from: https://ubuntu.com/download/server*

**Comment by pmahnke** [comment]
@sil2100 are you able to comment on this bug?

**Comment by sil2100** [comment]
I think this is no longer an issue, as I see no links to checksums from the server download pages. Also, it seems that it was an error from the start as `ubuntu-18.04.5-live-server-amd64.iso` images are hosted on `releases.ubuntu.com` not on `cdimage.ubuntu.com`, so the checksums for those can be found here instead: https://releases.ubuntu.com/18.04.6/SHA256SUMS (just currently we have .6 instead of .5).

So I think we can close this.
