### ISSUE TITLE
Clearing filters on `/certified?q=...` page takes you back to `/certified`

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#10325]
If you go to https://ubuntu.com/certified?q= and apply some filters, when the page reloads try to clear them and it takes you back to `/certified`. This is not the expected behaviour - clearing filters should keep you on search results page

**Comment by carkod** [comment]
I think if this is not expected, it requires some UX. Because unless you are in a `/certified/<category>` page, we don't have a starting point for the generic search, the starting point would be `/certified` according to original designs by Matthew, so in theory this follows the original designs.

If we don't do it this way, then you will end up in a search page with no query showing all results, which I think kind of defeats the purpose of search. E.g. Google will not take you to the search results page with an empty query.
