### ISSUE TITLE
[COPY UPDATE] Livepatch service

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/ubuntu.com#10486]
Please update Livepatch service from the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit?usp=drivesdk)

**Comment by fitojb** [comment]
Do you guys happen to know whether there’s also the need to update the service name for the localized strings of `software-properties`? I ask because the new release is imminent and there won’t be enough time for volunteer translators to make the necessary changes, unless somebody `sed`s all the PO files.
