### ISSUE TITLE
MarkupSafe has released a breaking change

### ISSUE THREAD

**Issue by mtruj013** [canonical-web-and-design/ubuntu.com#11260]
## Summary

MakrupSafe has released a breaking change which breaks dotrun

## Process

Run `dotrun` and see error `ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ubuntu/dotrun-projects/ubuntu.com/.venv/lib/python3.8/site-packages/markupsafe/__init__.py)`

Relevant jinja issue: https://github.com/pallets/jinja/issues/1587

**Comment by davidism** [comment]
It looks like you are not pinning your dependencies. Use something like pip-tools to pin dependencies so you control when updates happen.

**Comment by carkod** [comment]
Does this replicate when you run the docker image?

**Comment by nottrobin** [comment]
Thanks @davidism for reaching out. Yeah it would be nice to be properly pinning dependencies. I'd prefer to do that by moving to a modern package manager like poetry - something like pip-tools feels a bit like a hack. Do you have thoughts on that?

We don't import Jinja directly [in this project](https://github.com/canonical-web-and-design/ubuntu.com/blob/main/requirements.txt), so if we're getting 2.x it must be because something else is asking for it (Flask, presumably?). Worth looking into. Thanks.

**Comment by davidism** [comment]
The Pallets projects all use pip-tools to pin the development environment. Requirements files are the lowest barrier to new contributors compared to needing to install another application first, although those new project management tools have been tempting occasionally. I've also been impressed by [PDM](https://pdm.fming.dev/), if you want to consider it too.

Not sure what's pulling in an old version in that requirement file. The cool thing about pip-tools is that it will output a requirements file that has comments saying which other requirements each requirement came from, so you'd be able to trace what required Jinja2<3.
