### ISSUE TITLE
ubuntu.com/certified home page server block is missing Dell and has incorrect counts for HPE and Lenovo

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#11907]
## Summary

The listing of Vendors in the server block does not list at least the top three server vendors.  In addition it shows incorrect numbers.

First, it only shows HPE and Lenovo. It should, at the very least, also be showing Dell. I am pretty sure Dell used to be there, and has disappeared.

Additionally, all the vendor listings show an incorrect number of certificates for Server (I did not sanity check anything else)
Lenovo is listed as "Lenovo (219)" but if you click on Lenovo there are only 79 certificates in the results.
HPE is listed as "HPE (90)" but if you click through, there are only 58 results.

Doing some digging on the back end and I suspect those counts include certificates marked "Private" and they should NOT.  Those numbers should only reflect the number of public certificates (i.e. the ones that appear when you click through to a particular vendor search such as 

https://ubuntu.com/certified/servers?vendor=Lenovo

I realize that last is probably an API issue so I'll point skay at this too.

## Process

Go to https://ubuntu.com/certified and look at the Servers section.
Note that Dell is no longer listed
Also note that Lenovo shows 219 certificates and HPE shows 90, both of which are not correct.

## Current and expected result

Current: Server block only only shows HPE and Lenovo
Expected: Server block at least shows Dell, HPE and Lenovo and if we must show counts, the counts reflect public certificates only and do not include private ones in the count.

## Screenshot

![Screenshot from 2022-07-28 21-32-51](https://user-images.githubusercontent.com/4295496/181664492-270f48c4-631e-4d4e-a74f-cf3b6785ab79.png)

**Comment by codersquid** [comment]
The api filters out private certs. I can dig more in to what is going on tomorrow..

**Comment by codersquid** [comment]
The reason Dell is missing is that the API is returning _Dell Technologies_ as the vendor and there is logic in the template that exactly tests for _Dell_. (It checks for three specific vendors since the list of server vendors is so lengthy).

https://certification.canonical.com/api/v1/vendorsummaries/server/

https://github.com/canonical-web-and-design/ubuntu.com/blob/main/templates/certified/index.html#L128

If I recall correctly, the vendor used to come back as _Dell EMC_ and we were asked to change it to _Dell Technologies_. I don't know that we ever displayed _Dell_ if that was the case. Good catch.

As for counts, I don't know why that is happening. Nothing has changed in the API in forever. Maybe it's that the section on servers isn't using the same api as the other sections for historical reasons. I'll dig into that.

**Comment by codersquid** [comment]
The count is correct in https://certification.canonical.com/api/v1/certifiedmakes/ instead of the other api.

I've made changes locally to use that the same way the other types are being use it (the change is straightforward), but I can't get dotrun to work right now to check the changes. Maybe I can make a wip PR to resort to using the demo that spins up.
