### ISSUE TITLE
Flash of unstyled text on page load

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/ubuntu.com#4756]
## Summary

Due to a performance issue, a new user will see text unstyled before the Ubuntu font kicks in.

**Comment by nottrobin** [comment]
Unfortunately this isn't fixed by https://github.com/canonical-websites/www.ubuntu.com/pull/4750, as we thought it might be. I just tested it, it doesn't seem to have any effect at all.

**Comment by pmahnke** [comment]
@barrymcgee and @nottrobin next steps?  should I close this for now?

**Comment by barrymcgee** [comment]
@pmahnke Yes, I think we exhausted any options we had in Malta at the time - is that your view @nottrobin?

**Comment by nottrobin** [comment]
I dunno. It still unsettles me. I don't think this issue is high priority, but I would like to leave it open if we can. I'm not quite sure we definitely exhausted all options. I feel that there there should be a way to hold off on first paint until the font has downloaded, or maybe inline the fonts, or at least make it so the titles display at the same time as the rest of the text.

**Comment by nottrobin** [comment]
This could maybe be addressed through [the `font-display` rule](https://font-display.glitch.me/), but it doesn't look like https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5226#issuecomment-500450043 implements it correctly.

**Comment by barrymcgee** [comment]
@pmahnke It works!

**Comment by matthewpaulthomas** [comment]
The `font-display` rule was removed in #5886.

**Comment by barrymcgee** [comment]
@matthewpaulthomas A local override has been added via https://github.com/canonical-web-and-design/ubuntu.com/pull/5893 until the change can be made upstream in Vanilla.

**Comment by SirSamTumless** [comment]
I am closing this. If you need to re-open it please make actions for it.

**Comment by nottrobin** [comment]
:cry:
