### ISSUE TITLE
Copy docs destination url

### ISSUE THREAD

**Issue by WendyS1000** [canonical-web-and-design/ubuntu.com#5317]
When I click at the bottom of the page on ubuntu.com to view an associated copy doc, I am directed to a Google Drive folder and not the copy doc itself. 

To replicate this:
Go to https://ubuntu.com/kubernetes/managed
Click on the yellow tab at the bottom "propose changes to this page to the copy document

---
*Reported from: https://ubuntu.com/kubernetes/managed*

**Comment by bartaz** [comment]
I think the issue is with template inheritance.

Kubernates templates are extended from "/templates/templates/base.html" that doesn't have `meta_copydoc` block, so even when copydoc location is defined in templates it's ignored.

Kubernates pages templates should be either extended from `/templates/base_index.html` or `meta_copydoc` block needs to be added to "/templates/templates/base.html".
