### ISSUE TITLE
Chrome Edge Preview lists page as unsafe

### ISSUE THREAD

**Issue by ross01ed** [canonical-web-and-design/ubuntu.com#5489]
Go to https://lists.ubuntu.com/archives/ubuntu-announce/2018-October/000237.html in Edge Preview (you can get it at https://www.microsoftedgeinsider.com/ ) and you will see:

This site has been reported as unsafe
Hosted by lists.ubuntu.com
Microsoft recommends you don't continue to this site. It has been reported to Microsoft for containing harmful programs that may try to steal personal or financial information.
Microsoft Defender SmartScreen

![unsafe](https://user-images.githubusercontent.com/11042102/61625331-5ee7a780-ac72-11e9-9bbd-212048e79e2d.png)

---
*Reported from: https://ubuntu.com/*

**Comment by evilneuro** [comment]
To be fair, classic Edge does the same thing, meaning that the problem is not with Canonical, or the MS Chromium Edge development team, but with the MS Defender SmartScreen team.

![Annotation 2019-07-24 150630](https://user-images.githubusercontent.com/93133/61800354-c7768600-ae24-11e9-8775-0f461786261d.png)

**Comment by ross01ed** [comment]
After using the contact form on the SmartScreen page, and also using other channels (contacting the Edge team via their feedback form), this seems to be working now.
