### ISSUE TITLE
U.c/advantage should link to the wiki FAQ

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-web-and-design/ubuntu.com#6070]
We should add a prominent link to the UAclient wiki / FAQ.

https://wiki.ubuntu.com/UAclient

---
*Reported from: https://ubuntu.com/advantage*

**Comment by matthewpaulthomas** [comment]
I appreciate the effort that’s gone into writing the wiki page. It may be a useful source for developing contextual help. However, it’s really not appropriate to link to the page directly, for four reasons:

1. If there’s evidence of people having a particular issue, it would be addressed much more effectively by adjusting the page design, or adding contextual help at the relevant place in ubuntu.com/advantage, rather than hoping people will follow a link and find the answer somewhere in one long separate page.
2. Even if it was a good idea to provide help on one long separate page, that page should be on the same site (for example, ubuntu.com/advantage/help), so that “Advantage” is still present in the navigation, not on a different site.
3. Even if it was a good idea to have help on a different site, it should not be on the Ubuntu wiki, which is for Ubuntu contributors, not end users. (help.ubuntu.com and docs.ubuntu.com would both be less-bad choices.)
4. Even if it was a good idea to put help on the Ubuntu wiki, the text would need substantial revision to be appropriate for end users.

**Comment by pmahnke** [comment]
@matthewpaulthomas I agree that we should do your no. 2 - how can we get that created?

**Comment by BryanQuigley** [comment]
It was decided to make the Wiki page the FAQ for this - because we could do it in the shortest time.  Again I'm happy for these to be owned elsewhere - but there are MANY pages used for these purposes on the wiki such as:

https://wiki.ubuntu.com/Kernel/Livepatch
https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase (and all subpages)

We also want these to be updated quickly.

Both pages I maintain Livepatch and this one are locked down so only Canonical employees can edit.

**Comment by matthewpaulthomas** [comment]
@pmahnke I’ve reported #6099 for creating a help page on ubuntu.com.

@BryanQuigley I appreciate this is a wider issue than just UA. However, as far as I’m aware, your two examples have never been linked from ubuntu.com either (and ubuntu.com uses the phrase “knowledge base” for something else entirely). They also illustrate some of the kinds of issues I’d like to prevent here. For example, on that Livepatch wiki page, you have listed its availability for HWE on 16.04 and 18.04 LTS; meanwhile, [the equivalent info on ubuntu.com](https://assets.ubuntu.com/v1/ef19ede0-Datasheet_Livepatch_AW_Web_30.07.18.pdf) lists it for HWE only on 14.04 LTS. I think we should be able to update pages quickly without the solution involving contradictory pages.

For security pages, Joe and Dean have both approved of a general proposal to move user-facing security info to ubuntu.com as well (as Dean put it, “to appear more official and less happenstance”), including security notices and CVE pages.

**Comment by BryanQuigley** [comment]
To be clear, I'm fine with that responsibility moving to the main site - and the teams in question.  We (support) needed a public way to cover common questions - as these are both public so we can't use support's normal KB. 

That PDF is quite out of date and IMHO not a convenient way for customers to find that info.

**Comment by anthonydillon** [comment]
The branch adding this link had a number of concerns. Therefore, closing until this issue is fleshed out.
