### ISSUE TITLE
Free contract prominent when the user has paid for account

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#6086]
Issue reported by Uros.

> After investigation with frankban, it looks like some users get confused about their enterprise subscription and just see the instructions to attach machines to their personal free one
We have a customer that attached 70 machines to free contracts, which was a red flag, but turned out they actually have 2 accounts, bought aws ua but missed the instructions to attach to ua standard, but used the free one instead
We should maybe reduce the importance of personal one if you have enterprise one (and hide it) hide = collapse instructions

@matthewpaulthomas could you take a look please.

**Comment by matthewpaulthomas** [comment]
Unfortunately I can’t test this behaviour because I don’t have a test account with a paid subscription. Could someone attach a screenshot of the initial state of the page after signing in?

However:

- If I understand [the code](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/advantage/index.html#L123) correctly, the attach+detach instructions for your first paid subscription are expanded by default (as they should be), and the paid subscriptions appear above the free one. Is that correct?

- [I specified](https://docs.google.com/document/d/1AW8wQu1Uvq0xFtd_c2JwNdic075MPOTx7k2KHqFPPeo/edit#heading=h.pqw61dxfaqjj) that you should need to click a “Get your token” button to generate the token and reveal the instructions for your free subscription.

  ![image](https://user-images.githubusercontent.com/19801137/68541983-9358ae00-039e-11ea-93ce-f4b14640dd7f.png)

  Then the UA team decided that everyone should have a free subscription by default, to save the server from having to remember whether each person had asked for it or not. Unfortunately, the end result is that before clicking anything, someone using only a paid subscription will see instructions for a free subscription that they’re not using. I think this issue could be addressed by implementing the original proposal of remembering whether someone has requested a free subscription or not, and showing instructions only if they have. If that’s not practical, next best would be remembering the expanded state client-side (with a cookie or similar).

**Comment by matthewpaulthomas** [comment]
> Could someone attach a screenshot of the initial state of the page after signing in?

I was finally able to try the page with paid plans, thanks to #7042:

![image](https://user-images.githubusercontent.com/19801137/78469713-97a1b100-771b-11ea-8f75-dee7a1fc7762.png)

> Unfortunately, the end result is that before clicking anything, someone using only a paid subscription will see instructions for a free subscription that they’re not using.

Maryan has now again reported that this is a problem for customers.
