### ISSUE TITLE
[Whitepaper - VMWare to Openstack] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6090]
## Requirements

We're going to use the same the takeover and engage page from the VMWare to OpenStack webinar:

- [Engage page](https://ubuntu.com/engage/vmware-to-charmed-openstack) and it's copy [doc](https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit#heading=h.8ev345nols5h)
- Takeover
![Screenshot 2019-12-05 at 10 24 45](https://user-images.githubusercontent.com/28983816/70226866-7c14a280-1749-11ea-9408-4e37ecffe64a.png)

 
- [x] Update takeover
- [x] Update engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 ready for you https://github.com/canonical-web-and-design/web-squad/issues/1967

**Comment by Khutch25** [comment]
FYI, we don't need a new engage page built for this, I am going to suggest adding it to the existing page - https://ubuntu.com/engage/vmware-to-charmed-openstack. I will add edits for this engage page as comments in the copy doc today!

**Comment by Khutch25** [comment]
Added my edits to the existing webinar page into the abstract - https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit?usp=sharing

**Comment by anasereijo** [comment]
@sowasred2012 this is ready for you

**Comment by Khutch25** [comment]
Reviewed [this page](https://ubuntu-com-canonical-web-and-design-pr-6242.run.demo.haus/engage/vmware-to-charmed-openstack#) and here are my edits, which have all been laid out in [the copy doc](https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit?usp=sharing):

- Can that first paragraph be removed, with the text starting at 'Due to the costs associated with..."
- There's no form on this page for the whitepaper, can that be added in? The form ID is in the copy doc
- Can a link be added to the 'From VMware to Charmed OpenStack' webinar mention in the second to last paragraph?
- Visually, I think it would be nice to have the third paragraph from the bottom be turned into bullets as Whitepaper highlights

@SirSamTumless @sowasred2012

**Comment by sowasred2012** [comment]
@Khutch25 no probs - on the note about turning the paragraph into bullets, does this work?

This whitepaper:
- compares VMware’s proprietary virtualisation offerings with an open-source approach, Canonical’s Charmed OpenStack
- presents the economic and efficiency benefits of taking an open-source approach
- provides a detailed cost analysis highlighting the savings an organisation can make by migrating from VMware to Charmed OpenStack

**Comment by Khutch25** [comment]
Thank you, @sowasred2012! Can the 'Download the whitepaper' link in the CTA direct to the top of the form, bypassing the hero section? Otherwise, we should probably remove it, as it's an empty link. 

Also can the highlight bullets look like the one on this page:
 https://ubuntu.com/engage/cloud-init-whitepaper
Screenshot here:
![WP_engage_ex](https://user-images.githubusercontent.com/42180941/70451302-0720d000-1a9d-11ea-8a85-40068cb4a25d.png)

**Comment by sowasred2012** [comment]
@Khutch25 yep, that's done!

**Comment by Khutch25** [comment]
Thank you, @sowasred2012! +1 from Marketing :)
