### ISSUE TITLE
/blog “Events and webinars” includes one that’s a year old

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6114]
1\. In the ubuntu.com footer choose “Blog”
2\. Scroll near the bottom

What you see: An “Events and webinars” section with three items, one of which is [“Ubuntu, security & compliance”](https://ubuntu.com/blog/ubuntu-security-compliance)

What’s wrong with this:
- The linked page invites you to “join our webinar on November 28th”, which would be fine, except that it means November 28th 2018
- It discusses “heading into 2019”, which is no longer the case

What should happen: either
- the post is revised to remove the outdated references, or
- ubuntu.com/blog no longer links to it.

One way to achieve the latter would be by retiring the post. Another way would be to adjust the “Events and webinars” section so that it doesn’t link to any items more than, say, six months old.

---
*Reported from: https://ubuntu.com/blog*

**Comment by RCMainak** [comment]
I would like to fix this issue.

This issue can be fixed by passing a date six months old from now to the following function call https://github.com/canonical-web-and-design/canonicalwebteam.blog/blob/64dee702eb2cd871b3a06a65e3812d1e8f1af2ef/canonicalwebteam/blog/common_view_logic.py#L48

The function accepts date in the after parameter which will only return the desired events.

Should I submit a PR in the [canonicalwebteam.blog](https://github.com/canonical-web-and-design/canonicalwebteam.blog) repo with aforementioned change?

**Comment by pmahnke** [comment]
@RCMainak thanks for offering.  You are more than welome to submit a PR.  Just so you know, there is a larger issue of whether our Marketing team (who does events) want to continut to post events on the blog.  This is why there are no events, they haven't been promoting them this way for a few months.  But in the case they do, the PR would be helpful.

Peter

**Comment by RCMainak** [comment]
@pmahnke I have created a PR for now. If any changes needed let me know I will update the PR accordingly.

**Comment by matthewpaulthomas** [comment]
Verified that the section no longer appears. Thanks @RCMainak.
