### ISSUE TITLE
/advantage: Not obvious that “Attached” reveals paid subscription token

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-web-and-design/ubuntu.com#6136]
These are items I've had to clarify on the help wiki (#6099) or with customers. 

 * It has not been obvious that you can click on Attached to get your enterprise subscription link. Wording might be better to, maybe change to Attached Computers.

----

 * ~~I believe many customers may be using their personal subscription because it's much more obvious. If they have enterprise subscriptions, the free subscriptions should be behind another click.~~ — _already reported as #6086_ 
 * ~~FIPS and CC-EAL don't do anything today, we should not encourage anyone to run those commands~~ — _now reported as #6154_
 * ~~Needs some sort of thought flow when customer has more than one subscription, there is not remotely enough info there for them to decide which on they should attach.~~ — _now reported as #6155_
 * ~~Client shows actual customer account name, website doesn't.~~ — _now reported as #6156_

Aside from FIPS/CC, these may all help fix each other depending on the chosen UI change.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by matthewpaulthomas** [comment]
Thanks @BryanQuigley, this is useful. I’ve split this into separate issues so we can get on to them right away.

**Comment by anthonydillon** [comment]
Could this PR have resolved this issue? https://github.com/canonical-web-and-design/ubuntu.com/pull/6083

**Comment by matthewpaulthomas** [comment]
@BryanQuigley To expand on that question from Ant — We think it should now be obvious that you can click on “Attached” to reveal the instructions+token, because:
- the instructions+token for your first paid subscription is revealed by default
- on November 15th, #6083 was released, which visually connects those expanded instructions+token to the “Attached” cell immediately above it
- November 15th is also when you reported this issue, so none of your customer questions would have been from after that date.

If you’re still getting customer questions about how to do that particular, we’d be interested in any more details you can get, in particular:
- how many subscriptions they have
- what (if anything) they tried before asking for help.

(BTW, in case you weren’t notified, we’d also appreciate your feedback in #6155 and #6156. Thanks!)

**Comment by BryanQuigley** [comment]
#6083 is a very nice improvement.  haven't had any more customer issues - but hasn't been that long.  Will wait a week or so and then close this if no more occur.  Thanks!

**Comment by matthewpaulthomas** [comment]
@BryanQuigley Hi, any further reports from customers not finding the token?

**Comment by BryanQuigley** [comment]
Nope, I think everything that has come up is covered in other issues.  Closing this, thanks!
