### ISSUE TITLE
hide hero section from pages 2>

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6406]
If we click on page 2 (and more) the page loads showing the navigation and hero section. We then have to scroll to see the cards and so on.

I suggest doing what we currently have on [blog](https://ubuntu.com/blog?page=2). When loading other pages we lose the hero section.

**Comment by anasereijo** [comment]
I would like to know your opinion on this @matthewpaulthomas

**Comment by matthewpaulthomas** [comment]
> I would like to know your opinion on this @matthewpaulthomas

- The old tutorials.ubuntu.com does not have a “hero section”, and [my design](https://docs.google.com/document/d/1KwkyPUASE3EyYQlHM6iPN_AWBIAkKkNuz53QAr1TDxo/edit#heading=h.ra6k5dqgbldj) does not either. So I suggest dropping it from every page, including the first page. My design does have a heading and two intro sentences, but I don’t think that’s enough to deserve a padded coloured strip.

- Making “You can write your own.” the second sentence in the intro paragraph (as I wrote it), rather than a standalone link, would also reduce the height of the intro section. (If you really want it to be separate, it would be better as just “Write your own >”.)
