### ISSUE TITLE
fix titles hierarchy in tutorials content

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6409]
At the moment titles within a tutorial are displayed in a bigger font than that section title. See below

![Screenshot 2020-01-15 at 17.46.19.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/aaf47ffd-38ea-40eb-9e75-613ece50196c)

I think we should display those titles in a smaller font. See below.

![Screenshot 2020-01-15 at 17.45.10.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/92bcdcfe-1f2d-40f2-ae8b-413b3f232da9)

**Comment by anasereijo** [comment]
@matthewpaulthomas I would like to know your opinion about this. Thank you!

**Comment by matthewpaulthomas** [comment]
@anasereijo I think you’re right that the page section headings should be lower-level than the step title, since they are “inside” the step.

But I think the code is easier to follow and maintain if we don’t skip any levels — the tutorial title should use `<h1>`, the step title `<h2>`, and top-level headings within a step `<h3>`. For example:

> # `<h1>`Juju charm development (part 1)`</h1>`
> ## `<h2>`8. Next steps`</h2>`
> ### `<h3>`Layers versus charms`</h3>`
> …
> ### `<h3>`How to think about ‘Reactive programming’`</h3>`
> …

Does that mean the tutorial title should be bigger than it is now? Not at all. We’re using a different method of showing its importance, putting it in a grey strip by itself _instead_ of making it big. So we could give it a dedicated class — like the `<h1 class="title">` that tutorials.ubuntu.com uses — and then `.title {font-weight: inherit; font-size: inherit}`.

Similarly, in future, we might decide to change the `<h2>`step title`</h2>` from using a big font size to some other presentation (small caps, coloured background, horizontal rule below, fancy bullet…), but that would not alter the fact of it being the second level of heading on the page.
