### ISSUE TITLE
[18.04.4] Update download/raspberry-pi page for new images

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6533]

**Comment by sowasred2012** [comment]
From Lukasz on IRC:

"the only thing that might be good to consider changing (maybe not now, but in the nearest future) is for instance this core page: ubuntu.com/download/raspberry-pi-2-3-core, since now core18 supports Pi4 as well"

"So the things that might be nice for changing there are: mentioning that Pi4 is supported and just providing a single link to our 'pi generic' images (so no more "Ubuntu Core 18 image for Raspberry Pi 3." but more like one "Ubuntu Core 18 image for Raspberry Pi".)"

**Comment by pmahnke** [comment]
@sowasred2012 I have added Lukasz comments as a task for me... so I will close this.
