### ISSUE TITLE
Missing tutorial - The "Linux command line for beginners" tutorial has not been imported

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/ubuntu.com#6546]
The tutorial located at https://github.com/canonical-web-and-design/tutorials.ubuntu.com/blob/master/tutorials/desktop/command-line-for-beginners/command-line-for-beginners.md has not been moved to https://discourse.ubuntu.com/c/tutorials.

**Comment by tbille** [comment]
It seems that there is another one: https://github.com/canonical-web-and-design/tutorials.ubuntu.com/blob/master/tutorials/packaging/advanced-snap-usage.md

After investigation about the reason why they weren't imported it seemed that the reason is that their content is too long for discourse: `Body is limited to 32000 characters; you entered 69999.`

This is the advanced snap usage with the correct new format: https://pastebin.canonical.com/p/d3JbtTwHrS/

We should maybe split this tutorial in 2?

**Comment by tbille** [comment]
Tutorials uploaded: 
https://ubuntu.com/tutorials/command-line-for-beginners#1-overview
https://ubuntu.com/tutorials/advanced-snap-usage#1-introduction
