### ISSUE TITLE
<button> elements in the search box have an invalid alt attribute

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/ubuntu.com#6728]
I think that `title` is the desired attribute

![image](https://user-images.githubusercontent.com/118614/74931883-7a698b00-53d8-11ea-819d-f499fa52f38b.png)

**Comment by matthewpaulthomas** [comment]
I don’t think the button needs a `title=`, because its position and icon design makes it obvious that it’s a Clear button. Any text should be specifically for people who can’t see the position or icon design.

I’m not a fan of using `<i>` for the icon, but since it’s there and it has CSS specifically for hiding any contents, we can put a “Clear” label inside it.
