### ISSUE TITLE
Visiting a tutorial hides the header

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6974]
1\. Go to [ubuntu.com/tutorials](https://ubuntu.com/tutorials).
2\. Choose any tutorial where its first step is taller than your viewport, and wait for it to load.

What you see: The page is scrolled to hide the navigation, which would reassure you that you’re on the correct site. It also hides the tutorial title, making it harder to check that you’re on the correct tutorial.

![image](https://user-images.githubusercontent.com/19801137/75155691-7905ce80-5708-11ea-8940-f4fd1f873902.png)

What you should see: When visiting a tutorial, the whole header should be visible by default.

This is a sequel to:
- #6407 where @anasereijo reported the same problem. It was closed by #6414, despite @barrymcgee giving QA–1 (“I still see the jump downwards”).
- #6842, which I reported (not having seen #6407) covering that problem and a Back navigation problem, because I assumed they were related. It was closed by #6963, which fixed the Back navigation problem, but still not the scrolling.

**Comment by steverydz** [comment]
We spent a long time discussing this as tutorials was going live and decided to stick with the browsers default behaviour because there isn't a workaround that won't cause a problem in at least one browser.

If we really want to change the behaviour then we'll have to revisit the way the tutorial page works and move the tab switching to JS rather than using CSS which I don't think anyone is keen to do.

Perhaps this needs more discussion:?

**Comment by anthonydillon** [comment]
Yes I believe this requires more discussion and reasoning as to validate the change. If someone follows a link to a tutorial surely the tutorial content is more important them showing them the navigation of the site?

**Comment by matthewpaulthomas** [comment]
@steverydz What do you mean by “the browser’s default behaviour”? I don’t experience the same behaviour on, for example, [Microsoft’s C# tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/) or [W3Schools tutorials](https://www.w3schools.com/) or [the cplusplus.com tutorial](http://www.cplusplus.com/doc/tutorial/). This is a problem with ubuntu.com pages in particular, not browser behaviour in general.

Specifically, the page is apparently telling the browser to redirect from, for example, [tutorials/install-jre](https://ubuntu.com/tutorials/install-jre) to [/tutorials/install-jre#1-overview](https://ubuntu.com/tutorials/install-jre#1-overview), which is part-way down the page. I don’t think the browser is wrong to follow the page’s instructions. I think the page is wrong to ask the browser to do that in the first place.

@anthonydillon If this was seriously desired behaviour, then:
- We would do it on every page, not just tutorial pages. (Even if we assumed that navigation was superfluous for subsequent tutorial steps, that wouldn’t apply to the first step, for the reasons I gave originally.)
- Other sites would do it too (or we’d have a really good justification for doing our own thing).
- #6407 would have been closed with an explanation of why we think it’s a good idea, rather than an unsuccessful attempt at fixing it.

**Comment by sowasred2012** [comment]
From talking about it with @steverydz last week, we tried a few different approaches for tackling this, but couldn’t seem to satisfy requirements, which seemed to be:

- The ID of the current tutorial step should be present in the URL, even if you’ve just arrived at the first step from /tutorials.
- It should use CSS `:target` as a means of showing/hiding tutorial steps, so that users without JavaScript enabled can still navigate through them.

What I tried initially was having the first step of the tutorial visible when coming from /tutorials, using just CSS. [A method I’ve used to do this before](https://github.com/canonical-web-and-design/canonical.com/blob/master/static/sass/_pattern_tabs.scss) involves reversing the order of the steps in the markup, and then applying CSS to ensure the “first” (actually the last, as far as the markup is concerned) step is visible if there is no current `:target`.

As Steve pointed out, since this method reverses the order of the steps in the markup, the problem with this approach is that it could have an adverse effect on SEO.

The second approach I thought about was to just not do the redirect we currently do to the first step in the tutorial, and instead use classes that are applied/removed with JS. While easy enough, it would most likely make navigating through the tutorial impossible for users without JS enabled.

The third approach we tried (that I too eagerly created a PR for) was to simply scroll the window back up to the top of the page on page load. This worked as expected on Firefox, but not on Chrome, where the closest we could get was to delay the scroll for a split second. The scroll jump was plainly visible, and didn’t look good.

We wondered about a fourth approach, where the ID of the first step is appended to the tutorial link on /tutorials, but that would involve some backend work, and we would still need to somehow handle the page automatically scrolling to the element with that ID.

**Comment by matthewpaulthomas** [comment]
> - It should use CSS :target as a means of showing/hiding tutorial steps, so that users without JavaScript enabled can still navigate through them.

I’m impressed that the tutorials work without JS! Though on initial load, the section area is blank (just as it was with Back in #6842).

One way to fix both that issue, and this one, would be for each step to actually be a separate page, with `/tutorials/`{name-of-tutorial} being step 1. Then for people with JS, you could return to nearly the current loading speed (and, if you really wanted, scroll to the step heading when navigating between steps) by using `XMLHttpRequest()` to get the step contents, like `fetchDropdown()` does now.

Alternatively, here’s a simple (though slightly evil) hack that fixes just this issue:
```css
.l-tutorial-section {
    display: none;
    position: relative;
    margin-top: -9rem; // update whenever global nav height changes, last updated 20200309
    padding-top: 9rem;
}
```

**Comment by sowasred2012** [comment]
> Alternatively, here’s a simple (though slightly evil) hack that fixes just this issue:
> 
> ```css
> .l-tutorial-section {
>     display: none;
>     position: relative;
>     margin-top: -9rem; // update whenever global nav height changes, last updated 20200309
>     padding-top: 9rem;
> }
> ```

Just tried this out on Firefox, and yay! It works. Tried it out on Chrome, and nay; it does not work.

**Comment by barrymcgee** [comment]
Relevant? https://web.dev/snap-after-layout/
