### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#7228]
## Summary

Complete search functionality. Add:
- Ubuntu version and release search
- Priority and package

**Comment by steverydz** [comment]
This issue is covered by:
- https://github.com/canonical-web-and-design/ubuntu.com/issues/7927
- https://github.com/canonical-web-and-design/ubuntu.com/issues/7929
- https://github.com/canonical-web-and-design/ubuntu.com/issues/7924
- https://github.com/canonical-web-and-design/ubuntu.com/issues/7926
- https://github.com/canonical-web-and-design/ubuntu.com/issues/7928
