### ISSUE TITLE
CVE pages design review

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#7267]
The CVE pages as they stand haven't had any visual design. The specific areas that need attention are:

- The table on both the main CVE page and Ubuntu CVE page which needs to show status and priority
- The priority/CVSS base score badge on the Ubuntu CVE page

## Resources
- [Design spec](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit) 
- [Existing table](https://people.canonical.com/~ubuntu-security/cve/main.html)

### Main CVE page
This includes the table

![main_cve_page.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/1222c158-7fac-456e-8dea-bca52cdcf0ad)

### Ubuntu CVE page
This includes the table and the priority/CVSS score badge

![ubuntu_cve_page.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/bdefe506-b908-45a2-9eb5-3bc6f1991337)

### Non-Ubuntu CVE page
![non_ubuntu_cve_page.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/84877e9f-fffb-498a-bc1e-082cc86086b4)

### Reject CVE page
![rejected_cve_page.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/db102a61-da16-4c32-9962-04419db3d4bd)

**Comment by steverydz** [comment]
@SirSamTumless This is the ticket for visual design on the CVE pages which is needed. Who can I assign this to?

**Comment by SirSamTumless** [comment]
@spencerbygraves is your man!

**Comment by steverydz** [comment]
@spencerbygraves can you take a look at this please? Hopefully it won't take up too much of your time. I think @matthewpaulthomas should be able to answer any questions around the meaning of the colours etc.

**Comment by spencerbygraves** [comment]
>The table on both the main CVE page and Ubuntu CVE page which needs to show status and priority

@matthewpaulthomas has requested some new icons to use here, can we review the design for this when they are completed?

>The priority/CVSS base score badge on the Ubuntu CVE page

@matthewpaulthomas can we use the existing [Vanilla label](https://vanillaframework.io/docs/patterns/labels) here?

**Comment by steverydz** [comment]
I think using the label would be good - we'd need some rules about which colours apply to which status i.e.
- critical (deprecated label)
- high (in progress label)
- medium (updated label)
- low (validated label)
- negligible (new label)

Would the CVSS base score also be a label?

**Comment by spencerbygraves** [comment]
@steverydz given the limited colours, maybe we could do the following:

- Critical - deprecated
- High - deprecated
- Medium - in progress
- Low - new
- Negligible - validated
- Base score - updated

There will be some Vanilla work on notifications next cycle, which would include status colours I think. But this is what we have in Vanilla for now.

@matthewpaulthomas what do you think?

**Comment by steverydz** [comment]
@spencerbygraves @matthewpaulthomas In regards to the tables, do we go live as is then for now? I assume the icons won't be ready this week and the aim is to go live by the end of this week.

**Comment by steverydz** [comment]
Here's what it looks like with the label styles:

![cve_page_with_status_badge](https://user-images.githubusercontent.com/501889/79847663-edcb5100-83b7-11ea-8add-e993cbba7ca0.png)

**Comment by steverydz** [comment]
@anthonydillon raised this point about the search filtering here: https://github.com/canonical-web-and-design/ubuntu.com/pull/7242#issuecomment-617158683

> There is no clear explanation of what is being filtered and how to clear them

**Comment by spencerbygraves** [comment]
@steverydz the table and labels look fine to me. I think we could come back and add the icons.

@matthewpaulthomas?

**Comment by anthonydillon** [comment]
@steverydz I would suggest prefilling the fields with query params. And adding a simple neutral button to clear all filters which loads /cve.

**Comment by steverydz** [comment]
@anthonydillon that sounds like a good idea. The fields are already populated in the latest branch so this would mean just added a link to /cve styled as a button. I'll get that done.

**Comment by steverydz** [comment]
@anthonydillon I've added the clear button in this pr: https://github.com/canonical-web-and-design/ubuntu.com/pull/7300

**Comment by matthewpaulthomas** [comment]
> @matthewpaulthomas can we use the existing Vanilla label here?

Unfortunately not, because:

- There’s no reasonable mapping between Vanilla label classes, which denote states of Vanilla patterns themselves, and CVE priorities. (It would be an amazing fluke if there was!) For example, making High and Critical the same colour, as proposed above, would be needlessly confusing.

- Even if we used Vanilla label colours for priorities themselves, we couldn’t use those colours unchanged for these priority badges, because then the icons inside the labels would be invisible (judging by examples of the new icon language I’ve seen so far, which have no borders bevels or shadows). Instead we’d have to use lightened versions of those colours (as I suggested in [the wireframe](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.9a0ml5bppl8c)), or maybe a coloured border with no fill.

- Originally I sketched priority value and CVSS 3 Base Score as having equal size and vertical position on the page, CVSS just being less colourful. Multiple members of the Security team responded that this was still a misrepresentation, because while they’re related, Ubuntu priority is _much_ more important than CVSS 3 Base Score. I addressed this by introducing three differences: priority (a) above, (b) larger, and (c) having a border/fill while CVSS did not. Using Vanilla labels for both, as shown above, would remove all three differences and therefore reintroduce the misrepresentation.

> @anthonydillon raised this point about the search filtering here: #7242 (comment)
>
>>  There is no clear explanation of what is being filtered and how to clear them

I don’t think CVE pages should have any filter function, because so many of the use cases involve entering search criteria up-front that relegating them to filters (and therefore needing to add “Clear”, “Apply”, etc) would waste more time than it saves.

**Comment by steverydz** [comment]
In regards to the design of the labels/priorities/scores etc I need someone to make a call on what this should be otherwise I can't move forward with it.

> I don’t think CVE pages should have any filter function, because so many of the use cases involve entering search criteria up-front that relegating them to filters (and therefore needing to add “Clear”, “Apply”, etc) would waste more time than it saves.

So my understanding from this is that you can search by id or search by package - not both together. In which case having one search button for all fields seems confusing?

Isn't priority then a filter?

**Comment by steverydz** [comment]
@matthewpaulthomas sorry, should have mentioned you in [the above comment](https://github.com/canonical-web-and-design/ubuntu.com/issues/7267#issuecomment-619850444)

**Comment by steverydz** [comment]
@matthewpaulthomas is my understanding of the CVE search in [this comment](https://github.com/canonical-web-and-design/ubuntu.com/issues/7267#issuecomment-619850444) correct?

Right now all three fields are parts of the same form and can be submitted at once. I'm not sure how it should work if they're all separate as there is only one cta button?

**Comment by steverydz** [comment]
@matthewpaulthomas I could really do with a steer here. I'm confused about how this form is supposed to work as your earlier comment suggests that it isn't correct right now. See https://github.com/canonical-web-and-design/ubuntu.com/issues/7267#issuecomment-619850444

**Comment by steverydz** [comment]
In [this draft PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/7348) I have split each field into their own forms so CVE ID is one form, Package is one form, and Priority is one form.

After re-reading [the UX document](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit) I believe the following is correct:

The CVE ID and Package forms are submitted by pressing "Enter". The Priority form uses JS to submit the form on change although without JS it will still work using "Enter".

When entering a query into CVE ID and only one result is returned the page redirects to that results page.

@matthewpaulthomas does this sound right to you?

**Comment by matthewpaulthomas** [comment]
Whoops, sorry @steverydz, I just didn’t see this the past few days.

> So my understanding from this is that you can search by id or search by package - not both together. In which case having one search button for all fields seems confusing?

Going directly to a CVE by ID could have been presented in its own form, separate from the search form, with just an “ID” field and a “Go” button.

For simplicity, we reuse one of the fields in the search form instead. For that reason, whenever you enter a CVE ID, we disable all the other controls (including the package field) and change the “Search” button to “Go to CVE”.

You can, however, search by _description_ and package together (for example, just CVEs that mention “HTTPS” in the “firefox” package). Or package and priority together (e.g. High/Critical CVEs in the “gnome-shell” package), or priority and version together (e.g. Critical CVEs in Ubuntu 20.04 LTS), or priority and component together (e.g. High/Critical CVEs in Universe), etc.

> Also isn't priority then a filter and therefore be separate from the search form?

Up to this point, the only mention of priority in this issue was icons and badges, not the search form.

Filters are useful where people are likely to (a) make a first selection with either a text search or category browsing, then realise (b) there are too many results and they want to see a subset that isn’t a subcategory (for example, filtering by colour or brand or price).

That isn’t the case for priority: there are no categories to browse, and it will be common for people to want to do a search that does not involve any text (for example, Critical CVEs in Ubuntu 20.04 LTS).

So, priority is part of the single search form — just like description, package, component, Ubuntu version, and status are.

**Comment by steverydz** [comment]
Thanks @matthewpaulthomas. That makes sense. I had a catchup with Carlos last week and we came to the same conclusion so the search has been updated with this behaviour.

We've start building the spec for phase 2 where we add the ubuntu version/status fields and icons/colours for status and priority to the tables: https://docs.google.com/document/d/1ns0OxQVnICxgq2xGsvWz6YFMUJgQI35Vsqy1yOokhko/edit#heading=h.jz4u82m8ty7t
