### ISSUE TITLE
UA purchase: Build product selection

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7571]
@matthewpaulthomas commented on [Tue May 26 2020](https://github.com/canonical-web-and-design/master-epics/issues/153)

**Comment by sowasred2012** [comment]
By @SirSamTumless, from https://github.com/canonical-web-and-design/web-squad/issues/2791#issuecomment-644737145 
(copied here as it's pertinent to this issue too):
> ### Shop dev chat
> Tuesday, June 16⋅1:00 – 2:00pm
> 
> - There is a worry about relying entirely on Javascript as a solution, so will need a fallback form. Peter would like the form to work without Javascript and then be enhanced. Steve thinks that React would be fine, but recommended View as it is lightweight. Ant would much prefer things to be loaded with the Python, as the core experience is the products - if they fail then we have no experience. We also have more experience as a team with Python solutions. In saying that, Ant built Image builder using Vanilla-Javascript. 
> 
> - There may be issues when it comes to the differences and dependencies of product attributes. The further you following through the purchasing process, the more we may have to rely on React. 
> 
> - Steve; this year we've introduced things that have to be more interactive than ever before. If this progresses, using a framework may be an option.
> 
> - Steve and Scott going to pair over a potential solution.

The desire amongst the dev team is to make sure the page is progressive i.e. functional if JavaScript is not available for any reason. 

We spoke about using a framework like React of Vue, but feel that both might add too much overhead for a number of reasons, so we're going to investigate much more lightweight options that allow a page to be dynamic if JS is available.

**Comment by SirSamTumless** [comment]
### PdM meeting product selection show and tell
_Mark, Will, MPT and Lech_

Instead of saying what kind of machine, can we instead say what are you setting up. If you have more than on kind under the set of machines.

Where can I see things like Apps, Openstack, Ceph. Doesn't like that we're phasing this, thinks it is bad decision. Lech to talk MPT through the Apps story as it is the primary thing we're trying to do.

Doesn't know if the wireframe MPT shared is the best solution. The dynamic is most of infra is the OS (which is kernel, livepatch, etc). The price of infra is 1500, but in a server is it 3000, combine it is 3400. It doesn't make sense to pay for infra or the combined thing if I just want Apps.

![Screenshot 2020-07-29 at 12.11.20.png](https://images.zenhubusercontent.com/5cb4608c97df763a9090bdeb/0d0617fd-0fb2-4804-ada6-46ff1e32abc4)
