### ISSUE TITLE
UA renewals: Clarify whether payment info is saved

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7602]
There’s confusion about whether payment details are being saved for future use.

If they are, then the current renewal UI is fine.

If they aren’t, then either:
- that should be fixed, or
- “Save payment details” should become “Continue” or similar.

**Comment by alnvdl** [comment]
It's rather that we don't support retrieving customer payment information for reuse later (by design), so instead we must ask for it everytime. So the button label "Save payment details", though techincally correct, may be confusing, since we will have to ask for a payment method again if there's more than one renewal.

**Comment by matthewpaulthomas** [comment]
Thanks @alnvdl. From call with Uros: Reusing saved payment details will be implemented once the UI design for automatic renewals is done.

Therefore, until then:
- “Save payment details’ should be “Continue”
- correspondingly, “Saving…” should be “Checking details…”.

[Spec updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#bookmark=id.3rl2z6wxg7fw).
