### ISSUE TITLE
CVEs: Implement priority+status explainer popup

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7763]
[From the CVEs spec](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.32o4oau13zr0):
> ![image](https://user-images.githubusercontent.com/19801137/84777681-d1bfe680-afd9-11ea-92af-a200ce4c13a4.png)
>
> When you focus or mouse over a table cell, an “ℹ️” icon should appear to indicate that you can click it or press Enter to reveal info on the current priority and status. (The icon should not be there all the time, to reduce noise in a table with hundreds of status cells.)

**Comment by steverydz** [comment]
@matthewpaulthomas has someone written copy for each of these priority/statuses?

**Comment by cassiocassio** [comment]
Silly question: Perhaps this is obvious: what kind of vanilla thing is this? @lyubomir-popov ? Is just a big tooltip (it's got the pointy bit), or is it a based off a p-subnav thing because you get it on click rather than mousever? (yet it doesn't go anywhere)...

If we don't have one, a "popup explainer" would be a useful thing.

It would allow links to documentation, where the text here isn't enough / allow us to keep the text in the explainer succinct.

**Comment by lyubomir-popov** [comment]
We don't have it in vanilla, but it is used in maas for example:

![image](https://user-images.githubusercontent.com/2741678/84908760-c7bae800-b0ac-11ea-97be-9c68b2919500.png)

A somewhat similar popup from snapcraft, minus the pointy triangle:

![image](https://user-images.githubusercontent.com/2741678/84908836-e325f300-b0ac-11ea-88d7-041bf267ed84.png)

And a while ago we removed the triangle from the contextual menu, so we should probably make a decision whether we want it or not and apply that to all cases. Currently, the local implementation in maas, and the vanilla tooltip are the only things that feature the triangle.

To do that, though, we need to have "depressed" states for anything that can trigger something like this, which we currently don't in vanilla.

**Comment by steverydz** [comment]
Copy to be taken from this page: https://people.canonical.com/~ubuntu-security/cve/priority.html

**Comment by steverydz** [comment]
Making space for this icon causes a lot of text wrapping:
![cve-table-with-icons--hover.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/712ab580-d937-48d2-b570-bf3751a6007a)

**Comment by steverydz** [comment]
@matthewpaulthomas I tried implementing this yesterday but having a second icon in the table cells is problematic. As you can see in the previous comment it causes excessive wrapping, especially in the case of "Does not exist".

I tried not adding any right padding and just positioning the icon in the top right of the cell, but then in some cases it overlaps the text.

I wonder if we could solve this by using a key for the colours and icons. I actually think this would be useful anyway because there is nothing to explain what the colours or icons mean as it stands.

What do you think?

**Comment by matthewpaulthomas** [comment]
@steverydz Your screenshot has six version columns, but staging.ubuntu.com has four (and in #7991 I’ve proposed four to five). That explains part of the wrapping.

If it’s still a problem after resolving that, two things could help:
- As mentioned in #7991, we could use a smaller font size for the table as a whole. (I think this would be reasonable, since only the first column relies on people distinguishing individual characters — all the other columns use whole words.) We’d need advice from @lyubomir-popov, though, for example on whether reducing the font would entail reducing the cell padding too.
- Since the icon should appear only on mouseover/focus, we could have it appear _over top of_ the right end of the cell, which for long statuses would mean over the top of the end of the status text.

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas @steverydz padding is in rems, so it only changes when the root font size changes. Chaning the text in a cell won't affect it.

**Comment by matthewpaulthomas** [comment]
@lyubomir-popov Sorry, I was unclear. I meant that if we reduce the size of all the text in a table (and the icons too, I suppose), _should_ we also reduce the cell padding proportionally?

**Comment by matthewpaulthomas** [comment]
@albertkol What is your question here?

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas sorry I've missed your question from a month ago, only saw it now when I got an email notification.

I wouldn't modify padding on the table. Proportionally scaling UI makes sense at site level, but I don't think it does on individual component level. It can only lead to inconsistencies, and creates grey areas - e.g., a reasonable question then would be: If one cell had a more important text which is set in the default font size - should pading within the table vary? I don't think we'd want that.

**Comment by albertkol** [comment]
@matthewpaulthomas summary:

- `font size` of the text in the cell has been reduced from `1rem` to `0.8rem` and the `line hight` was reduced to make the cell more complact, since there will be some extra wrapping

- We have no texts for the following statuses: `needs triage`, `needed`, `deferred`, `ignored`, `released`, `DNE`
It would be nice to have something even if it's temporary. Right now cells with those statuses will show no status explanation in the tool-tip.

- `Not vulnerable` and `Does not exist` do not show any priority explanation in the tool-tip because it does not show a priority icon in the cell.

- `Does not exist` does not display the information icon since it's missing status explanation (mentioned above) and has no priority icon

Some screen shots:
1)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/3b7c680e-179d-4487-8e4c-57d348fedab7)
2)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/c56b23e9-0186-416c-89cd-28d3b5da4eea)
3)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/c40f65dd-e650-45a9-aa2e-3eeb73f10e24)
4)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/535353d6-3490-40d9-a2f0-bad29ae76368)
5)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/a3b7771a-37a7-46e0-9150-1a37c916a878)
