### ISSUE TITLE
CVE search doesn't show 1 result

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7785]
search for 'CVE-2020' it says 3 results, shows 2, says you are looking at 1-20 results.

it should either count better or show all the results... the pagination should reflect the lower number of results.

![image](https://user-images.githubusercontent.com/441217/84909956-3482b200-b0ae-11ea-81bc-24d58ed6c099.png)

also filtering without a  search term doesn't return anything, you would think it would return cves matching that fileter

---
*Reported from: https://staging.ubuntu.com/security/cve?q=CVE-2020

**Comment by steverydz** [comment]
So far I've fixed the search result count issue in https://github.com/steverydz/ubuntu.com/tree/fix-cve-search.

@nottrobin @carkod The issue around the missing search result is because `CVE-2020-5249` has no items in `cve.active_status_tree`. Is this due to a faulty CVE or is something in the model not right?

**Comment by carkod** [comment]
This looks like package that is not longer active, so we might want to filter it out in the views
