### ISSUE TITLE
Display package source on CVE page

### ISSUE THREAD

**Issue by albertkol** [canonical-web-and-design/ubuntu.com#8264]
If you go to people.canonical.com you will see that every package has a source. (fx: https://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-8834.html )

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/088b6e8b-77ff-4093-8a6f-2dcedf6acf96)

We need these displayed on ubuntu.com too.

**Comment by albertkol** [comment]
@matthewpaulthomas would it be ok if we display this in the same cell with the package name?

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/122c4806-a6e1-47fa-94b0-15bba9ff3f54)

**Comment by matthewpaulthomas** [comment]
That’s a reasonable place to put the links. A couple of small tweaks:
- Instead of “Source:” and the package name repeated, can we just link the original display of the package name?
- Instead of putting the other links in brackets, can we use small text? Like this:

  linux
  <sup>Launchpad, Ubuntu, Debian</sup>

Thanks!
