### ISSUE TITLE
ubuntu.com/security/* inconsistent plurality

### ISSUE THREAD

**Issue by mssalvatore** [canonical-web-and-design/ubuntu.com#8300]
## Summary

Two new pages are being added under ubuntu.com/security
1) ubuntu.com/security/notices
2) ubuntu.com/security/cve

For the sake of consistency, it would be nice to standardize on either plural or singular. "notices" and "cves" make the most sense to me.

**Comment by matthewpaulthomas** [comment]
Thanks for this suggestion.

I think the URLs are fine as they are for these reasons, most important first:
1. Ubuntu Security Notices are found at **ubuntu**.com/**security**/**notices**, which is nice.
2. “cve”, on the other hand, is more easily recognisable than “cves” would be (unless we capitalized it as “CVEs”, which would be a pain).
3. /security/cve acts as the parent of the /security/cve-yyyy-nnnn URLs, while avoiding repeating “cve” (like it would if the URLs were /security/cves/CVE-yyyy-nnnn). On the other hand, /security/usn and /security/lsn would have been less recognizable than “/security/notices” is.
4. Singular CVE is consistent with the previous URLs (~ubuntu-security/cve/).
5. Plural notices, but “cve” rather than “cves”, is consistent with those other vendors I’ve found that have advisories and CVEs under different paths:
  - [access.redhat.com/errata](https://access.redhat.com/errata) (plural), [access.redhat.com/security/cve](https://access.redhat.com/security/cve) (singular)
  - [lists.suse.com/pipermail/sle-security-updates/](https://lists.suse.com/pipermail/sle-security-updates/) (plural), [suse.com/security/cve/](https://suse.com/security/cve/) (singular).

I think the most likely reason this might ever change is if we need to stop displaying USNs and LSNs in the same listings and search results — in which case they’d probably split into /security/usn and /security/lsn. But I’d rather avoid that for reasons 1 and 3 above.
