### ISSUE TITLE
Pricing seem wrong

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8392]
Even though I am sure there is a just reason for the difference it is jarring and confusing for users.
![image](https://user-images.githubusercontent.com/1413534/94692099-0dcd4c00-032a-11eb-8484-0bab78aa464d.png)

10 × US$25/year = $250
Subtotal: $235.53

**Comment by matthewpaulthomas** [comment]
Thanks @anthonydillon. “The same date as your existing annual subscription” is meant to convey that you aren’t buying a full year. Instead, you’re being charged for the period from the moment you purchased, on 30 September 2020, to the moment your existing subscription ends on 9 September 2021.

9 September 2021 – 30 September 2020 = 344 days
$235.53 / (10 × $25) × 365 days = 343.1 days

(The difference between 344 and 343.1 is because you’re being charged by the second rather than by the day, which is [a separate problem](https://docs.google.com/document/d/1kRqawNqi3ISXPqGohaAyu-QQEJlrGZiVv-Bn8bQfago/edit?disco=AAAAKWWt1v4).)

One way to make this clearer might be changing
> Subtotal: $235.53

to

> For this period: $235.53

What do you think?

**Comment by anthonydillon** [comment]
I think the real issue here is that I believed I was purchasing a brand new subscription and in that case would expect the support to cover the full year from today. 

I assume this has something to do with an existing contract but I am not expecting this subscription to be add additional quantity to an existing contract but be entirely separate.

**Comment by pmahnke** [comment]
Perhaps the message could be more like 'Prorated to end on the same date as
your existing subscription'

However, what if there was 1 more day on the existing sub?  I that would be
odd, pay £0.68...

**Comment by matthewpaulthomas** [comment]
> I am not expecting this subscription to be add additional quantity to an existing contract but be entirely separate.

Agreed. However, it’s a limitation of the contracts service that each customer can have only one subscription per level×machinetype combination. For example, you can have a UA Infra Standard Desktop subscription, and a UA Infra Advanced Desktop subscription, and a UA Infra Virtual Server Advanced subscription, happily separate … but if you then try to buy another UA Infra Advanced Desktop subscription, instead of becoming your fourth subscription, it’s added to your second one. (I can see how this would be useful for slowly growing a fleet over time, but it’s weird for subscriptions that might be for different teams in a large organisation. Hopefully we can make enlarging a separate feature eventually.)

Meanwhile, though, that’s not actually the reason for the prorating! if you have just a UA Infra Standard Desktop subscription, then you buy a UA Infra Advanced Desktop subscription, it will _still_ be prorated to match the first subscription, even though they’re different levels. Why? So that each customer has only one _annual payment_ (and/or, later, one monthly payment). Which I guess saves on payment fees.

> Perhaps the message could be more like 'Prorated to end on the same date as your existing subscription'

I hadn’t even encountered the word “prorated” until last month, so I’m leery of using it in UI. I’d rather “For this period: $235.53”, or maybe even “For period to 9 September: $235.53”.

> However, what if there was 1 more day on the existing sub? I that would be odd, pay £0.68...

Yes, quite odd. The current plan (not implemented yet) is that if there’s less than 30 days left, we’ll give you the choice of (a) paying prorated for those few days or (b) paying in advance for a subscription that doesn’t start until the other one ends/renews.

**Comment by anthonydillon** [comment]
I agree the solution proposed is the best in this situation.

The true solution would be to fold:
- Each new subscription, truly is a new subscription.
- Provide the ability to increase the quantity of an existing subscription which is a much clear course of action when someone wants to increase there fleet. When displaying the over usage on the subscriptions list.

**Comment by ajbeattie** [comment]
@anthonydillon @matthewpaulthomas I noticed something related to this today that I think could be solved together with this in a pretty standard way.

Even with messaging about proration, it's not clear exactly what my 'current subscription' is. I think we can clarify this and the original concern of this issue a lot with something like this:

```*Your current subscription: $100/yr* 
Next billed July 6th, 2021

*Your subscription after this purchase: $300/yr*
Next billed July 6th, 2021

*Due today: $246.24*
Prorated from today to July 6th, 2021
```

**Comment by anthonydillon** [comment]
I don't think wording is the best solution for this, although it would help in the short term. We are likely to end up provide a lot of functionality to cover this issue. For example, if you have a subscription that is less then a month away from expiring and you buy a few machine subscription do we add that to the subscription that needs to be renewed or create a new subscription? The current thinking is we ask the user which option they want in that situation.

**Comment by ajbeattie** [comment]
@anthonydillon I feel that having multiple separate subscriptions (or even having the option) is not ideal UX, and not consistent with other similar services. 

For example, I have several VMs and a managed database from Digital Ocean. All of the separate services are billed on a single monthly subscription. When I add a new service, it is added to my existing subscription and I'm billed for the prorated amount between the current day and the next billing period.

Digital Ocean differs slightly from our model in that it bills at the end of the usage period (while we bill at the beginning of the period), so the prorated amount is added to the next statement instead of being paid upfront. However, I've also used many services that bill up front and present changes in the way I described above (current sub, sub after change, billed today), and I believe it's a straightforward way to handle things (e.g. not SaaS but my car insurance and internet service both use this model).

While I do think that there is a use case for a single organization having multiple different "sets" of the same products, I don't think that separate subscriptions are the way to do it.

Instead, I would propose that this be handled with separate _accounts_. For example, if org X has two department which need separate billing and access for their UA purchases, they would maintain 2 accounts - X Department 1 and X department 2. This is a practice I've seen with AWS and other cloud services at companies I've worked at previously.

In the future, we could add another abstraction (or allow accounts to be related), but for now I believe one billing cycle per account is the way to go, especially since users can already be part of multiple accounts (so we are already most of the way to the solution I mention above).

--

Ultimately, I believe that our current model is the best choice and we should strive to improve the experience around it so that it is clear to users:

- As you mention, adding UX for increasing quantity (without going through the purchase flow) and billing a saved card 
- Clearly indicating the link between entitlements and subscription amounts (certainly within a future billing overview page, and potentially in the dashboard as well)
- Updating UX so that the behavior/proration of adding a new product is clearly messaged, and making the process more connected to your existing subscription

**Comment by anthonydillon** [comment]
Thanks for the detailed explanation @ajbeattie. It is more clear now to me that account management is the level in which you purchase separate department subscriptions. I still think we are far away from a full account management system but sounds like the right direction to work towards.

For example, two teams in the same org can create separate accounts. Then add team members to the account. Some members of the team should have admin permission, allowing them to modify the account subscriptions and are automatically billed on the saves card.

**Comment by ajbeattie** [comment]
@anthonydillon agreed - we still have much to do around account and user management. Fortunately the back end representation of users and accounts is in good position for this - users can be part of multiple accounts and infrastructure is in place for controlling each user's level of access.

**Comment by matthewpaulthomas** [comment]
> **Your current subscription:** $100/yr

We’re conflating two different meanings of the word “subscription”.

When I say “one subscription per level×machinetype combination”, I mean one of the things represented by a row in /advantage’s “Your paid subscriptions” table (and by the “Your free personal subscription” section below it).

When @ajbeattie says “added to my existing subscription”, he means the single annual UA item on his credit card bill.

Using the same word for both in the UI would be confusing. It is already confusing us:

> While I do think that there is a use case for a single organization having multiple different "sets" of the same products, I don't think that separate subscriptions are the way to do it.

That makes perfect sense if “subscriptions” means “items on your credit card bill”, but not if it means “rows in the subscriptions table”. It is weird that when you make a subsequent purchase it might, or might not, be merged into one of your existing ≤9 rows in the subscriptions table, depending on what kind of plan it happens to be. Abolishing prorating and requiring separate accounts are not the only two ways of avoiding that weird behaviour.

**Comment by ajbeattie** [comment]
@matthewpaulthomas yes - based on my experience, `Subscription` should be reserved for the recurring billing/payments. 

The rows in the table I think would be more appropriately named `Resources` that you are `entitled` to. 

As for subsequent purchases, I think that the weirdness there is solved by having clearly differentiated UX for adding quantity to an existing resource vs. adding a new _type_ of resource.

**Comment by frankban** [comment]
Yes clarifying the terminology would be helpful, so that we are all on the same page.
I wrote today this [short document](https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/basic-concepts.md), please take a minute to read it, as it can help in this conversation and future discussions.
Let me know if anything needs to be clarified further.

I think @wgx has good mockups for the upselling experience, and I agree with @ajbeattie: being able to add more machines to an existing contract rather than having to build the same product again will surely help in making the experience more natural and compelling.
