### ISSUE TITLE
Small screens is unusable 

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8394]
On small screens the table of subscriptions is unusable:
![image](https://user-images.githubusercontent.com/1413534/94692745-ce532f80-032a-11eb-8aab-8bc80b16087c.png)

**Comment by sowasred2012** [comment]
@wgx @matthewpaulthomas @meralonso - wanted to get opinions on how we can solve this; there's so much data, and content - do we have an existing pattern in any of our projects that would suit?

**Comment by meralonso** [comment]
This table has always been a bit of a pain @sowasred2012 - we should redesign it at some point @matthewpaulthomas @wgx 

As a temporary solution I'd suggest to not compress the table on mobile, keep the desktop size and scroll horizontally. I've seen this practice on other websites i.e https://stamped.io/pricing - please check desktop and mobile versions

**Comment by matthewpaulthomas** [comment]
A couple of small possible improvements:
- Make the subscription name and plan type cells wrap their text, rather than ellipsizing.
- [Make the table headers diagonal](https://css-tricks.com/rotated-table-column-headers-now-with-fewer-magic-numbers/) at small widths.

> keep the desktop size and scroll horizontally

Could we keep the table’s first column fixed, while all the other columns scroll horizontally? (Like a “frozen” column in a spreadsheet.) Maybe that’s beyond CSS’s power at the moment.

**Comment by anthonydillon** [comment]
You could try the Vanilla responsive solution? https://vanillaframework.io/docs/base/tables#responsive

**Comment by anthonydillon** [comment]
This has been merged.
