### ISSUE TITLE
/advantage/subscribe - existing sub date and prorated price do not show up until second page in checkout dialog

### ISSUE THREAD

**Issue by ajbeattie** [canonical-web-and-design/ubuntu.com#8533]
When adding to an existing subscription, the first checkout page will show 1 year from the current date as the end of the purchase and will show the full price, but once payment details are entered and you click 'Continue', you see the prorated price and the current billing cycle end day as expected.

First checkout dialog screen:
<img width="820" alt="Screen Shot 2020-10-20 at 8 26 03 PM" src="https://user-images.githubusercontent.com/6845951/96661779-85cbd800-1312-11eb-8489-c5228e5941b0.png">

Second dialog screen:
<img width="800" alt="Screen Shot 2020-10-20 at 5 13 07 PM" src="https://user-images.githubusercontent.com/6845951/96651096-b4898480-12f9-11eb-9d2c-6b04257c8f4b.png">

**Comment by anthonydillon** [comment]
I believe the real issue here is the fundamental structure of purchasing addition quality on an existing subscription. We will remain in limbo until we have a resolution for this proposal: https://github.com/canonical-web-and-design/ubuntu.com/issues/8392#issuecomment-712927253.

**Comment by matthewpaulthomas** [comment]
I don’t think #8392 is related. This is a simple matter of two views presenting something that’s supposed to be identical, but isn’t. I guess the bug is either in [`ua-payment-modal.js`](https://github.com/canonical-web-and-design/ubuntu.com/blob/advantage-shop/static/js/src/ua-payment-modal.js) or [`set-modal-info.js`](https://github.com/canonical-web-and-design/ubuntu.com/blob/advantage-shop/static/js/src/advantage/set-modal-info.js) where the prorated date is being set the second time but not the first time.

**Comment by sowasred2012** [comment]
Fixed in https://github.com/canonical-web-and-design/ubuntu.com/pull/8567
