### ISSUE TITLE
Typo in introducing-ha-microk8s-the-ultra-reliable-minimal-kubernetes

### ISSUE THREAD

**Issue by iatrou** [canonical-web-and-design/ubuntu.com#8605]
At https://ubuntu.com/blog/introducing-ha-microk8s-the-ultra-reliable-minimal-kubernetes just above "About Canonical" there is a rogue "ENDS"

---
*Reported from: https://ubuntu.com/blog/introducing-ha-microk8s-the-ultra-reliable-minimal-kubernetes*

**Comment by pmahnke** [comment]
@campbieil is this how we end press releases, with the &lt;ENDS&gt;?

**Comment by carkod** [comment]
Thibaut replied that we want some kind of visual separation, so I added our usual Vanilla separation instead of the `<ENDS>`. The live page is cached it seems, but here is a preview (only Canonical employees) https://admin.insights.ubuntu.com/2020/10/15/introducing-ha-microk8s-the-ultra-reliable-minimal-kubernetes/
