### ISSUE TITLE
[UA shop handover] UA Shop: support for resuming purchases

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#8762]
## Summary
If a customer gives up trying to pay for a purchase (e.g., card is declined) and leaves the session (closes the tab), when they come back later, their account may be blocked for purchases, because the previous purchase is still ongoing.

## Process
1. Make a purchase, but fail to pay for it (use a test card that is always declined).
2. Close the session with the error being displayed and no payment concluded.
3. Come back later, and try to purchase again. It will be blocked (by design) in ua-contracts.

## Current and expected result
Right now, the customer is blocked from making a new purchase and cannot continue their existing purchase.
The expected result would be a warning or a similar thing saying "Click here to resume your last purchase". This is possible by reading the pending purchases attribute on the subscription, reading that purchase by ID and then deciding how to proceed.

In the long term, we will add support for purchase cancellation in ua-contracts. For now, the only options will be:
- to continue the last purchase attempt (when this issue is fixed)
- wait for it to expire in 23h (Stripe and ua-contracts handle that automatically)
- contact support before these 23h to have the purchase voided;

**Comment by sowasred2012** [comment]
Linking to a pertinent part of the ua-contract docs: https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/contracts.yaml#L641

If a user has a subscription with `pendingPurchases`, we should inspect them and see whether they're processing, or need a payment method (because a previous attempt to pay failed, they closed the browser tab, then came back later to reattempt). If they need a payment method, we could fetch the details of the purchase from the API, though it's not clear what's the best way for the user to resolve the issue:

- with a purchase attempt in this state, the user is unable to start a completely new purchase
- the products and quantities on the purchase attempt can't be changed
- for these reasons, the UX would somehow need to inform the user that they _need_ to complete their purchase in order to ever again be able to try to order anything other than what is already on the purchase in question
- the purchase attempt can't yet be cancelled, though this functionality is said to be on the way
  - being able to cancel a purchase attempt would make things a lot simpler, we could either allow the user to cancel it themselves (or proceed with a new payment method), or silently cancel it when the user returns to the page, allowing them to start their order from scratch.

What do you think @alnvdl ?

**Comment by matthewpaulthomas** [comment]
> for these reasons, the UX would somehow need to inform the user that they _need_ to complete their purchase in order to ever again be able to try to order anything other than what is already on the purchase in question

“Somehow” is understating it: that limitation seems quite customer-hostile. Why does it exist?

**Comment by sowasred2012** [comment]
> “Somehow” is understating it: that limitation seems quite customer-hostile. Why does it exist?

Simply because the ability to cancel an in progress purchase, or to override pending purchases with new purchases, doesn't exist yet. @alnvdl what's the status of purchase cancellation?

**Comment by sowasred2012** [comment]
@alnvdl @ClementChaumel I'm very out of the loop - is this still a valid issue?

**Comment by ClementChaumel** [comment]
I don't think we resolved it the way it was suggested here but we did add a warning on /advantage if there is a problem with the payment and a link to /payment-methods to resolve it.
So I think it's safe to close it, what do you think @alnvdl ?

**Comment by albertkol** [comment]
Closing. No longer relevant.
