### ISSUE TITLE
CVE with noindex tag

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#9003]
is there a reason why some of the CVEs have a noindex tag on their headers: `<meta name="robots" content="noindex">` 
page example: https://ubuntu.com/security/CVE-2017-17230

This was triggered by google search console. If this is intentional then we should filter out the CVEs that shouldn't be indexed out of [the sitemap](https://ubuntu.com/security/cve/sitemap.xml).

**Comment by albertkol** [comment]
It turns out we are setting the `robots` to `noindex` if `cve.status == 'rejected' or cve.status == 'not-in-ubuntu'`.

I do not know why, but it seems like we decided for it to behave like this from the get go. So it's probably on purpose.

Perhaps @nottrobin remembers why..

Should we remove these cves form the sitemap?

**Comment by nottrobin** [comment]
Can we see who made the change? Is there a commit message?

**Comment by albertkol** [comment]
@nottrobin it seems to be the first commit that kicked off the CVE work: https://github.com/canonical-web-and-design/ubuntu.com/commit/8dac8523ca164e7d82c24ac61d6dd0b52532b1c8

There is no commit message to help us out with this one.

**Comment by matthewpaulthomas** [comment]
As [I described it in the design spec](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.og46m3w8vk79):

> A rejected CVE page is barely interesting, the main use case being when a CVE has been withdrawn or superseded by another.
>
> Therefore, this page should be returned, instead of search results, when searching for that particular CVE ID — but it should not be included in results for any other search, nor indexed by general search engines (e.g. `<meta name="robots" content="noindex">`).
>
> Reflecting this, the page should be grey and perhaps (depending on visual design) should have a “Rejected” ribbon.

> Similar to a rejected CVE page, a not-in-Ubuntu CVE page is hardly interesting in itself. It exists mainly to reassure people that Ubuntu is not affected by a particular CVE.
>
> Therefore it should be returned, instead of search results, when searching for that particular CVE ID — but it should not be included in results for any other search, nor indexed by general search engines.

**Comment by nottrobin** [comment]
> Therefore, this page should be returned, instead of search results, when searching for that particular CVE ID — but it should not be included in results for any other search, nor indexed by general search engines (e.g. <meta name="robots" content="noindex">).

I don't understand this. Maybe I don't understand what a rejected CVE is, but I would assume that, yes, rejected CVEs are probably not as interesting to anyone as active ones, but still that CVE has a number, and so is official in that sense.

There are so many CVEs that people are mostly going to find them by searching for their specific CVE number on Google, or some other very specific content. If someone has a CVE number for a rejected CVE, and they search for it to try to discover that fact, why wouldn't we want them to discover that fact on our website?

I generally don't understand the desire to obscure public information that we have available to us. I can understand worrying about obscuring other useful information through a load of noise, but that doesn't seem to apply here, since there are so many CVEs anyway that you're only ever going to find any of them by searching for something quite specific.

I would suggest that we both allow Google to index these pages and also consider adding a search function for finding those CVEs if one desires. Although I do think it is reasonable to exclude those CVEs from the default search.

The same logic applies to not-in-Ubuntu, except even more strongly.

**Comment by matthewpaulthomas** [comment]
> Maybe I don't understand what a rejected CVE is

[Rejected](http://cve.mitre.org/about/terminology.html#cve_record_rejected) means “the CVE ID and associated CVE Record should no longer be used”. I have found three reasons that this can happen, and one way of thinking about this is to imagine what we’d have done if the upstream (cve.mitre.org) data model had distinguished them.

- If the data model had included a “Duplicate” status, for the duplicates we’d return a 301 Moved Permanently to the original, which would naturally mean that duplicates didn’t show up in search results. Unfortunately we can’t do that, because [duplicates are represented as Rejected](https://www.openwall.com/lists/oss-security/2013/10/11/1), so the human has to do the redirection manually by reading the text — but that does not change whether it’s a good idea for duplicates to show up in search results.

- If the data model had included a “Withdrawn” status, for issues that turned out not to be security vulnerabilities, for those we’d return a 410 Gone, and we’d be happy that they didn’t show up in search results. Unfortunately we can’t do that, because [those issues are represented as Rejected too](https://www.openwall.com/lists/oss-security/2013/10/11/1) (same reference), so the human has to read the text to understand the status — but again, that doesn’t change whether it’s a good idea for Withdrawn CVEs to show up in search results.

- If the data model had included a “Never used” status, for CVE IDs that were part of a block assignment that wasn’t used by the end of the year, we’d return 404 Not Found, and that would mean it wouldn’t show up in search results. Unfortunately [those issues are represented as Rejected too](http://cve.mitre.org/data/board/archives/2017-05/msg00030.html), but again, that doesn’t mean that they should show up in search results.

**Comment by nottrobin** [comment]
The point I come back to here is that I think the main way that people will find a CVE is by Googling for its CVE number (which will remain distinct in all cases, I believe). In all the cases you describe, it is unlikely that people will be looking for those CVE numbers, but not impossible.

"Duplicate" seems the clearest case to me. If someone finds a CVE number for a CVE they had heard about, but was later determined to be duplicate (unbeknownst to the user), again they would Google for the number. Now, as you say, if "duplicate" was an official status then I would still be concerned about returning a 301 to the canonical CVE. Although these CVEs might be different representations of the same security issue, they probably have different descriptions. And again, a 301 would prevent the user being able to find that CVE based on the CVE number, as Google would simply no longer index the duplicate CVE's page at all. I would suggest it would be much clearer to keep the page up but clearly mark is as "duplicate" with a link.

The same is true for "withdrawn". A user has an ID, they are looking for it. A 410 will remove it from Google's results, hence no way for the user to discover that the CVE is withdrawn.

The "never used" CVEs are a very odd one. My first suggestion would be to ask Security if they ever push these to our database. But that then leads me to another realisation - it's really Security's decision whether they put CVE information in our database. If they do, I would suggest that they do so because they think it might be useful information. So we should display it, as clearly as we can.

I am somewhat curious what other CVE hosts do with these CVEs, but even if they follow your suggestions I still think it's a mistake. We want people looking for CVEs to find what they need on ubuntu.com, and that includes people trying to find out about duplicate or withdrawn CVEs.

**Comment by matthewpaulthomas** [comment]
Okay, you’ve changed my mind about duplicate and withdrawn CVEs. You’re right that someone is unlikely to know that a CVE has become a duplicate or withdrawn. So a Web search that previously returned an ubuntu.com result shouldn’t stop returning that result later. Both Red Hat and Suse have publicly-indexed pages for duplicates. And because we can’t practically distinguish between never-used and those other kinds, we’ll have to index all Rejecteds. [Spec updated](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.og46m3w8vk79).

> Although these CVEs might be different representations of the same security issue, they probably have different descriptions.

(This is routinely avoided by removing the description: “All references and descriptions in this candidate have been removed to prevent accidental usage.”)

…However, that doesn’t apply to CVEs about software that’s never been in Ubuntu — because whenever that’s the case, it was always the case. The only reason we have [pages for those](https://ubuntu.com/security/CVE-2020-9064), at all, is to serve them directly as reassurance for people who search for _that specific ID_ when they are _already_ on our CVE page. Enticing people to visit the page from anywhere else — by including it in any search results, local or external — would be time-wasting at best.

> We want people looking for CVEs to find what they need on ubuntu.com

For CVEs that ever had anything to do with Ubuntu? Sure. For those that didn’t? No, there are much better sites for that.

**Comment by nottrobin** [comment]
> For CVEs that ever had anything to do with Ubuntu? Sure. For those that didn’t? No, there are much better sites for that.

Which are the better sites? There's https://cve.mitre.org/, which is ok, but if I search for "CVE portal", the first result is a piece of software for setting up your own portal, the second & third are "cvedetails.com", with cve.mitre.org being the 4th, then you've got Microsoft, RedHat, Cisco. The CVE system is distributed, split between many CVE Numbering Authorities (CNAs), of which [Canonical is one](https://cve.mitre.org/cve/request_id.html#cna_participants).

Canonical is proud of its security capabilities and interested in being a serious player in the security space. It seems to me that it would make every sense for Canonical to be providing a universal CVE portal. And if I were a user coming to our CVE section I would be very surprised to find it deliberately excluded any CVE.

However I do think the decision of whether we include every CVE lies with the Security team. But the existence of the "not in Ubuntu" status suggests to me that they do choose to push and show all CVEs. I really don't think it's our business, or necessarily in Canonical's interests, to be deliberately obscuring any data they choose to push.

**Comment by nottrobin** [comment]
@matthewpaulthomas I discussed this with @pmahnke and we decided to simply allow all CVEs that Security choose to push to us to be indexed. I've filed a PR to that effect.

**Comment by matthewpaulthomas** [comment]
> Which are the better sites?

cve.mitre.org and nvd.nist.gov.

> if I search for "CVE portal"

I don’t think that’s a realistic use case at all. And I haven’t found any other example of a vendor publishing indexed pages about CVEs that aren’t in any of that vendor’s software.

**Comment by nottrobin** [comment]
> I don’t think that’s a realistic use case at all. And I haven’t found any other example of a vendor publishing indexed pages about CVEs that aren’t in any of that vendor’s software.

Then Security can opt not to push those CVEs.
