### ISSUE TITLE
[/security/cve] cve webpages do not expose mitigation field/information

### ISSUE THREAD

**Issue by stevebeattie** [canonical-web-and-design/ubuntu.com#9017]
## Summary

The CVE pages do not expose mitigation information where the security team has annotated it in their tracker. This is information intended for customers to be able to mitigate a security issue while awaiting a fix to land in the Ubuntu archive.

## Process

Example: CVE-2020-28374

In the source tracker https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2020-28374 the mitigation section has been populated; however, that does not show up as a separate section in https://ubuntu.com/security/CVE-2020-28374 ; it only appears on the page waaaaaaaay at the bottom because the information has been copied to to the Notes section. 

The script that exports this information to the website endpoint may need to be fixed to include this section.

## Current and expected result

Mitiagation annotations that the security team makes get surfaced to users. Additionally, because mitigation steps often involve running commands, they need to not lose their formatting, or an agreed upon schem for formattion needs to be agreed upon.
(The Notes section also has some formatting expectations.)

**Comment by matthewpaulthomas** [comment]
I’m sorry I didn’t include this field in the design because I hadn’t encountered it in any of the CVEs I looked at.

For [the same CVE on the old site](https://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-28374) “Mitigation” is between “References“ and “Notes”.

Coincidentally, though, we plan to add a “Remediation” section with boilerplate for installing relevant updates whenever available. Because it will be both short and important, it’s likely to go high up the page. “Mitigation” is very closely related to “Remediation”, so perhaps they should be consecutive.

The old page also demonstrates that “not lose their formatting” includes “convert any indented line into a `<pre>` element”. @stevebeattie Is there other formatting we should know about?

**Comment by matthewpaulthomas** [comment]
[Design proposed](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.9a0ml5bppl8c). Very simple: a new “Mitigation” section between the “From the Ubuntu Security Team” section (when present) and the new “Remediation” section (which is then followed by the “Status” section).

**Comment by matthewpaulthomas** [comment]
@elioqoshi Could you take a look at this design please?

**Comment by stevebeattie** [comment]
@matthewpaulthomas re formatting, indented as pre-formatted is all we had with the old site, I think that's fine to continue in the new site.

The design looks good to me. One could possibly make the argument that the remediation section should come before the mitigation section, as we always recommend remediating by applying updates, and that mitigations should be used if for whatever reason remediation can't be applied (for example, publication of the remediation is still underway, or some other limitation prevents a user from applying an update).

Thanks!

**Comment by matthewpaulthomas** [comment]
@stevebeattie Thanks. I’ve swapped the order of Remediation and Mitigation as you suggested.
