### ISSUE TITLE
Handle Stripe failing to initialise

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#9018]
A customer saw this while trying to renew - the odd looking card input suggests Stripe failed to initialise, possibly because of an aggressive adblocker blocking stripe domains. Whatever the cause, it leaves the customer unable to make a purchase - perhaps we could show a message informing the user there was a problem, and point them to a sales contact?

**Comment by cmars** [comment]
I think we need more observability into the web UI on the client, so that we can handle these kinds of customer issues in production more effectively.

This isn't an area I'm too familiar with, but ISTR sentry.io has been used in the past to monitor some of our other client-side web apps. Can we add sentry instrumentation to collect the client-side errors that may be occurring?

Based on the screenshot above, it looks like the Stripe payment method iframe either isn't getting loaded into the page at all, or isn't being allowed to render and execute content properly. There are so many reasons that could be the case:
- Stripe is blocked by network policy.
- Javascript or other page content is being blocked. This could be from ad blockers, software agents enforcing security policy in the browser, other add-ons, toolbars, etc.
- Browser compatibility issues (not sure what browsers we actually test, what our requirements are, etc)

Adding the right instrumentation would go a long way toward finding the root cause.

**Comment by alnvdl** [comment]
It seems that multiple customers are having this issue currently, and apparently all of them on Windows 10.

I tested in Windows 10 (Chrome and other browsers, and some others did the same), but we couldn't reproduce it.

I tried selectively blocking the following JS paths:

- js.stripe.com
- q.stripe.com
- m.stripe.com
- m.stripe.network

But it kept on working. Blocking `js.stripe.com` breaks the page, and the modal doesn't even open, so that's probably not the reason. `m.stripe.network` looks weird and a prime candidate to blocking in some networks, but blocking it doesn't seem to cause the issue either.

I only had success in reproducing this when blocking:

- https://js.stripe.com/v3/elements-inner-card-*.html

Or, to make it look exactly like the screenshot, deleting the iframe node altogether.

I know that's not how one should debug these issues, but it's the best I could do with the limited information we have :)

**Comment by alnvdl** [comment]
We also heard from customer success management that apparently one of the customers who was having this problem was able to purchase via the shop. So it may be that the problem is in the renewal form alone (I thought they were the same).

**Comment by pmahnke** [comment]
@anthonydillon @nottrobin can you look at this? Do we have the metering required?

**Comment by anthonydillon** [comment]
Hi, @cmars @alnvdl we do have error tracking across the python and JS errors on ubuntu.com here: https://sentry.is.canonical.com/canonical/ubuntu-com/.

 Do you have access? If not, who should I give access too?
