### ISSUE TITLE
Making purchase fails if one subscription has expired in the past

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9089]
If a customer has multiple subscriptions (not contracts!), the first one from the list is being read without making any distinction about whether it is valid or not. In some cases, this list may contain invalid subscriptions from the past (e.g., one that expired due to lack of payment), and these should be ignored when determining which subscription to use to get the last purchase ID.

The right thing to do would be to go over the list returned by this endpoint and find the subscription with `status === "active"` (it is guaranteed that we will only have one active at a time in the canonical-ua marketplace). The reason this endpoints returns even deactivated or locked subscriptions is to let the user consult their previous subscriptions.

https://github.com/canonical-web-and-design/ubuntu.com/blob/0a01cd86d12ed18decdcf79d4bd6c0dce0e81593/webapp/views.py#L647

**Comment by ClementChaumel** [comment]
Hey! I believe this is the same issue as https://github.com/canonical-web-and-design/ubuntu.com/issues/9004
And we just now released a fix adding a `?status=active` filter to the API call: https://github.com/canonical-web-and-design/ubuntu.com/pull/9015

I think it works for now because AFAIK we don't show deactivated subscriptions in the shop (yet anyway)

**Comment by alnvdl** [comment]
@ClementChaumel You're right, that is the same as #9004, sorry!
