### ISSUE TITLE
iSCSI drive support

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9191]
**Outline**
Allow users to configure mounting a network file system exposed over iscsi as part of installation.

**Comment by elioqoshi** [comment]
As a reference, here is how Debian handles iSCSI in the installer:

![VirtualBox_Debian_05_02_2021_14_42_31](https://user-images.githubusercontent.com/5436686/107042375-f6afd680-67c1-11eb-9f95-606e253b10b5.png)

![VirtualBox_Debian_05_02_2021_14_42_41](https://user-images.githubusercontent.com/5436686/107042385-fb748a80-67c1-11eb-83b4-dd613ad728d0.png)

![VirtualBox_Debian_05_02_2021_14_42_55](https://user-images.githubusercontent.com/5436686/107042390-fca5b780-67c1-11eb-95eb-594febaa541b.png)

![VirtualBox_Debian_05_02_2021_14_43_18](https://user-images.githubusercontent.com/5436686/107042402-02030200-67c2-11eb-8c46-89258454d60f.png)

![VirtualBox_Debian_05_02_2021_14_43_51](https://user-images.githubusercontent.com/5436686/107042456-1646ff00-67c2-11eb-8f06-fab99688f036.png)

![VirtualBox_Debian_05_02_2021_14_44_27](https://user-images.githubusercontent.com/5436686/107042470-1941ef80-67c2-11eb-8474-e4a610898311.png)

I am unsure of the success state and how that looks like since I had no actual iSCSI target.

**Comment by elioqoshi** [comment]
This can be considered wrapped up. We can still look at polishing it up in the implementation stage. 

Reference specs: https://docs.google.com/document/d/1rsapWIKR9xR3sXE56WUEETSvnZkxJH4RqrvJCKK7IWI/edit#heading=h.v8vlh9f5o0cz
