### ISSUE TITLE
[UX fix] /financial-services strip is horrible

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9221]
Can someone look at this strip and propose a better solution to adding the whitepaper?

![image](https://user-images.githubusercontent.com/441217/107491595-4821e200-6b83-11eb-935b-c679fca3b1eb.png)

[copy doc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit?ts=601c07bc#heading=h.7y7b3q239v01)

**Comment by SirSamTumless** [comment]
@anasereijo Don't we have a WP downloadd module?

**Comment by anasereijo** [comment]
@pmahnke see below my proposal for that strip. I also took the chance and did a few visual improvements on the page (hero section + logo cloud and bottom section with canonical and ubuntu logos)

![Financial Services](https://user-images.githubusercontent.com/36884067/109687240-f5808800-7b7a-11eb-88c2-39032f7be79b.jpg)

**Comment by anasereijo** [comment]
this is looking good! just some small things:

- [ ]  hide the logos from "Drive business agility" on mobile version
- [ ] show the whitepaper section on mobile
- [ ] make "Trusted by executives. Loved by leaders." an h4
- [ ] show canonical and ubuntu logos on mobile otherwise the text doesn't make sense
- [ ] check any copy changes in the copydoc

Thanks!
