### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://contracts.staging.canonical.com/v1/marketplace/can...

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9277]
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/11747/?referrer=github_plugin

```
HTTPError: 400 Client Error: Bad Request for url: https://contracts.staging.canonical.com/v1/marketplace/canonical-ua/purchase/preview
  File "webapp/views.py", line 685, in post_advantage_subscriptions
    purchase = advantage.preview_purchase_from_marketplace(
  File "webapp/advantage.py", line 215, in preview_purchase_from_marketplace
    response = self._request(
  File "webapp/advantage.py", line 35, in _request
    response.raise_for_status()
  File "requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://contracts.staging.canonical.com/v1/marketplace/canonical-ua/purchase/preview
```

**Comment by SirSamTumless** [comment]
Any updates on this @ClementChaumel? Can it just be triaged?

**Comment by ClementChaumel** [comment]
That's the 'message': 'can only make one purchase at a time in yearly subscription' issue. The card was denied. the user will be able to retry in a day

**Comment by alnvdl** [comment]
@ClementChaumel The SimulatePurchase endpoint simulates exactly what would happen if you were to call the endpoint that makes a purchase, but returns a simulated invoice instead of the actual purchase. So any error that prevents the user from making the purchase can happen here.

One important thing is that this endpoint will return an error if you try to simulate a purchase without a credit card being set for the customer. So this endpoint should only be called after the customer is 100% ready to make the purchase, just pending the final confirmation. I think this missing card error is the one that is causing the most Sentry alerts. We could change this behavior if necessary. The reason it's currently like this is so that it matches 100% the `AddPurchase` endpoint, so you can have confidence that you are ready to call it if `SimulatePurchase` does not return an error.

So it's up to UX and you guys to decide what's best here.

**Comment by SirSamTumless** [comment]
@albertkol To add tracking on this issue to investigate how many of the tests fail.

**Comment by albertkol** [comment]
Set up a dashboard to track these better. Closing it.
