### ISSUE TITLE
Server responds that checkAuth call is not valid

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9284]
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/5111/?referrer=github_plugin

```
Server responds that checkAuth call is not valid
```

**Comment by SirSamTumless** [comment]
@jpmartinspt Could you please triage this?

**Comment by jpmartinspt** [comment]
No entirely sure why this happens, we might need to get in touch with someone from SSO.

**Comment by jpmartinspt** [comment]
After investigating this a bit, I don't think there is much we can do. This apparently gets reported because [talisker sets raven to report error logs](https://github.com/canonical-ols/talisker/blob/48a465c27619cf2aeabc1ab4dd276dff1b0c6707/talisker/logs.py#L175) and this is just something the [openid library logs when authentication fails](https://github.com/necaris/python3-openid/blob/5c7f8f8fa4d2a0124516046ab2f84130eb8c10cb/openid/consumer/consumer.py#L1164).

Will bring this up in catch-up to see and reopen if anyone thinks we should.
