### ISSUE TITLE
[Global login in navigation] Make the active search span the navigation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9291]
When search is active the input should span the entire header and we need to handle closing the search somehow.

**Comment by cassiocassio** [comment]
- when we benchmarked around, both [esc] and clicking outside the search closed the field

![Screen Recording 2021-03-25 at 09.53.52.mov.gif](https://images.zenhubusercontent.com/59391bc151aa2c305780dbd6/67d99b92-b983-4bcd-85d4-9914e579292e)

- The X in our field was originally the [reset] action, but we discussed about how nobody really uses that control 

- Now we're using the X for [close] and not [reset] should it be present from the start, rather than appearing after you start typing?

![Screen Recording 2021-03-25 at 09.37.45.mov.gif](https://images.zenhubusercontent.com/59391bc151aa2c305780dbd6/42268a25-1eea-43a4-9ec1-10a7f1d84aee)

(separate question)

-  Is the "please fill in this field" warning helpful, or telling the user something they don't know? Seems like a default from a much larger field patterns where you might have missed something/.

![Screen Recording 2021-03-25 at 09.38.35.mov.gif](https://images.zenhubusercontent.com/59391bc151aa2c305780dbd6/c07fc86e-6da8-472c-b3a9-dad377e79cb0)

-

**Comment by anthonydillon** [comment]
@cassiocassio this issue is in regard to [this demo](https://ubuntu-com-9450.demos.haus). Could you re-review from that, please?

**Comment by cassiocassio** [comment]
-  [esc] and (perhaps more important) clicking outside the field should both close the field. 

- I feel the light-box effect will be appropriate when we are wanting to help the user focus on a set of search suggestions, as @anasereijo sketched, I'm 5050 if it's needed/a bit heavy at this initial stage
