### ISSUE TITLE
UA token text box does not mention Livepatch

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#9359]
Hello! The text box that appears in the 'machines' column to display the UA token refers to ESM only, and not Livepatch. I think this will confuse several customers who are looking to enable Livepatch.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by elioqoshi** [comment]
This is how it currently looks like:

![image](https://user-images.githubusercontent.com/5436686/112972063-24752400-9150-11eb-8776-ee899831ad85.png)

![image](https://user-images.githubusercontent.com/5436686/112972225-54bcc280-9150-11eb-9bb7-e09bb7cf6f8a.png)

This issue is part of the whole table being a bit of a mess. We could include a `Do you want to enable Livepatch?` link which would switch the active dropdown to the livepatch dropdown as a short term solution. 

@wgx what do you think?

**Comment by wgx** [comment]
@elioqoshi Yep, Livepatch is a separate tab - we need to address this as part of a wider look at the table. Close this for now but we make a note to include this user need. :)
