### ISSUE TITLE
Add slider for representation of cost of public and private cloud

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#9524]
At `/openstack` build slider for graph to represent the difference in prices between public and private cloud. See the [comment](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?disco=AAAAIAiqPGY) in the copy doc.
- The TCO bar of public cloud should be lower (therefore green) than private cloud (red at this point) at first.
- As the VM hours increase, the private cloud TCO decreases and drops lower than public cloud and the colours of the bars swap. 

@waynecrosby has kindly offered to create a GIF to show how the slider should work. Here is a static image to show the graph:

![image](https://user-images.githubusercontent.com/58959073/114061468-63148800-988e-11eb-9e3c-3f579cda5f9e.png)

**Comment by waynecrosby** [comment]
@tytus-kurek Can you confirm this is how the slider should work in terms of the columns increasing/decreasing when the user adds more VM hours?
![Chart](https://user-images.githubusercontent.com/42238722/114066574-c5bc5280-9893-11eb-9491-04dc01e1b9be.gif)

**Comment by tytus-kurek** [comment]
@waynecrosby

Almost :). A couple of notes:

- The TCO column (both Public Cloud and Private Cloud) should always be a sum of CapEx and OpEx, while on the animation above it is not
- The Public Cloud OpEx column should be growing linearly to the VM hours in the slider; since it is not obvious from the attached animation, just please make sure that this is how it works
- The Private Cloud CapEx column should be static; at the moment it decreases ad the number of VM hours is growing
- The Private Cloud OpEx column should actually be static too and should be 1/3 of the Private Cloud CapEx cost
- Again, Private Cloud TCO should be a sum of Private Cloud CapEx and Opex and thus, it should also be static

I'm pretty sure you can easily fix it. I cannot wait to seeing the page live!

**Comment by carkod** [comment]
Hi @tytus-kurek just taking a look at this.

Do we have numbers for this?  What's the max and min number of hours? Or should we just use an estimated proportion e.g. 100 hours

Still, we need to know even if we use proportions, at which point should CapEx be static? Looking at the graph it could be around 1/7?

Thanks

**Comment by carkod** [comment]
@anasereijo do you know where I can find the Public cloud and Private cloud icons? Thanks!

**Comment by anasereijo** [comment]
> @anasereijo do you know where I can find the Public cloud and Private cloud icons? Thanks!

@carkod do you need the illustration with the text or without?

**Comment by carkod** [comment]
> > @anasereijo do you know where I can find the Public cloud and Private cloud icons? Thanks!
> 
> @carkod do you need the illustration with the text or without?

I guess it's always better to write it as plain text? So without.

**Comment by anasereijo** [comment]
@carkod 
[public cloud
](https://assets.ubuntu.com/v1/a3694a61-Public+Cloud.svg)[private cloud](https://assets.ubuntu.com/v1/f25ccac7-Private+Cloud.svg)

**Comment by tytus-kurek** [comment]
@carkod 

You can use any scale you want. 7 is totally fine, but I think the slider and charts would change more smoothly if you had more than that.

CapEx should always be static. Same for the private cloud OpEx. Even at 0/7.

The slider is supposed to replace the image.

Regards
