### ISSUE TITLE
Ubuntu Raspberry Pi 4 SSD supported image

### ISSUE THREAD

**Issue by Jack-0** [canonical-web-and-design/ubuntu.com#9771]
The download for "Ubuntu Server 20.04.2 LTS" server only work on SD cards. There is no easy solution for users to install Uuntu on USB connected SSD drives. It is possible however by using the steps mentioned in [this pi forum thread](https://www.raspberrypi.org/forums/viewtopic.php?t=278791). I'm hoping that Ubuntu could add an official version of Ubuntu server that supports SSD's i.e a version that has the latest firmware files and handles the compression steps.

---
*Reported from: https://ubuntu.com/download/raspberry-pi*

**Comment by SirSamTumless** [comment]
@rhys-the-davies Could you please take a look at this?

**Comment by rhys-the-davies** [comment]
Absolutely, I'll report back when I can tell you the blocker or hand you the solution @Jack-0

**Comment by rhys-the-davies** [comment]
Hey @Jack-0 o/ So, since focal point release 2 (20.04.2) there's no longer a need to decompress the kernel so an awful lot of that info can be thrown out. One of our engineers recently wrote a blog post about it: https://waldorf.waveform.org.uk/2021/you-boot-no-u-boot-first.html

But I'm happy to say that for the later releases (groovy onwards) it's even simpler: just flash the image straight to the USB drive and ... that's it

Obviously, our problem here is there's no documentation or central place for Ubuntu on the Pi information. To that point, stay tuned. Your issue here seems to have been the final piece of ammo I needed to get some people writing docs
