### ISSUE TITLE
The "Purchase Study Lab access" button performs no action.

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical-web-and-design/ubuntu.com#9867]
Ideally, we would like this button to be conditional, and either point to the purchase page (once that exists) or the Study Labs materials if the user has already purchased the Study Labs.

---
*Reported from: https://ubuntu.com/cube/study*

**Comment by SirSamTumless** [comment]
@jpmartinspt Can you have a quick 👀  at this?

**Comment by KellenRenshaw** [comment]
@jpmartinspt Have you had a chance to look at this?

**Comment by jpmartinspt** [comment]
@KellenRenshaw the cleanest solution I can think for this is to create a new view in ubuntu.com that we can link from the button, and in the view we hit the EDX API to check if the user has access to the study labs an redirect accordingly. The only issue with this is that the redirect might be a bit slow since we need to hit the API. Does it sound reasonable?

**Comment by KellenRenshaw** [comment]
I think that sounds excellent. We are planning to keep the Study Materials under the SSO login, so I don't see a problem with the view.
